name: lazy_load_scrollview
description: A wrapper for a ScrollView that will enable lazy loading
version: 0.0.1
author: Quirijn Groot Bluemink <quirijn.grootbluemink@gmail.com>
homepage: https://github.com/QuirijnGB/lazy-load-scrollview

environment:
  sdk: ">=1.19.0 <2.0.0"
  
dependencies:
  sdk: '>=2.0.0-dev.1.2 <3.0.0'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
